version: '3'
services:

  #-----------------------------------------------------------------------
  #--- ubuntu 2004 installed via dpkg ---
  #-----------------------------------------------------------------------
  #
  #    webserver listens on 8878
  #
  # to build+run this pair:
  #    docker-compose up pkg_ubuntu2004
  #
  # to destroy and remove it:
  #    docker-compose down pkg_ubuntu2004

  weewx_pkg_ubuntu2004:
    tty: true
    build: build/pkg_ubuntu2004
    container_name: weewx_pkg_ubuntu2004
    image: weewx_pkg_ubuntu2004:latest
    depends_on:
      - weewx_nginx_pkg_ubuntu2004
    volumes:
      - /var/tmp/weewx_html/html_pkg_ubuntu2004:/var/www/html/weewx
      - /var/tmp/weewx_archive/archive_pkg_ubuntu2004:/var/lib/weewx
  
  weewx_nginx_pkg_ubuntu2004:
    image: nginx
    container_name: weewx_nginx_pkg_ubuntu2004
    ports:
      - "8878:80"
    volumes:
      - /var/tmp/weewx_html/html_pkg_ubuntu2004:/usr/share/nginx/html

  #-----------------------------------------------------------------------
  #--- ubuntu 20.04 installed via setup ---
  #-----------------------------------------------------------------------
  #
  #    webserver listens on 8879
  #
  # to build+run this pair:
  #    docker-compose up weewx_setup_ubuntu2004
  #
  # to destroy and remove it:
  #    docker-compose down weewx_setup_ubuntu2004

  weewx_setup_ubuntu2004:
    tty: true
    build: build/setup_ubuntu2004
    container_name: weewx_setup_ubuntu2004
    image: weewx_setup_ubuntu2004:latest
    depends_on:
      - weewx_nginx_setup_ubuntu2004
    volumes:
      - /var/tmp/weewx_html/html_setup_ubuntu2004:/home/weewx/public_html
      - /var/tmp/weewx_archive/archive_setup_ubuntu2004:/home/weewx/archive

  weewx_nginx_setup_ubuntu2004:
    image: nginx
    container_name: weewx_nginx_setup_ubuntu2004
    ports:
      - "8879:80"
    volumes:
      - /var/tmp/weewx_html/html_setup_ubuntu2004:/usr/share/nginx/html

  #-----------------------------------------------------------------------
  #--- debian 10 installed via setup ---
  #-----------------------------------------------------------------------
  #
  #    webserver listens on 8889
  #
  # to build+run this pair:
  #    docker-compose up tar_deb10
  #
  # to destroy and remove it:
  #    docker-compose down tar_deb10

  weewx_setup_deb10:
    tty: true
    build: build/setup_deb10
    container_name: weewx_setup_deb10
    image: weewx_setup_deb10:latest
    depends_on:
      - weewx_nginx_setup_deb10
    volumes:
      - /var/tmp/weewx_html/html_setup_deb10:/home/weewx/public_html
      - /var/tmp/weewx_archive/archive_setup_deb10:/home/weewx/archive

  weewx_nginx_setup_deb10:
    image: nginx
    container_name: weewx_nginx_setup_deb10
    ports:
      - "8889:80"
    volumes:
      - /var/tmp/weewx_html/html_setup_deb10:/usr/share/nginx/html

  #-----------------------------------------------------------------------
  #--- debian 10 installed via dpkg ---
  #-----------------------------------------------------------------------
  #
  #    webserver listens on 8888
  #
  # to build+run this pair:
  #    docker-compose up pkg_deb10
  #
  # to destroy and remove it:
  #    docker-compose down pkg_deb10

  weewx_pkg_deb10:
    tty: true
    build: build/pkg_deb10
    container_name: weewx_pkg_deb10
    image: weewx_pkg_deb10:latest
    depends_on:
      - weewx_nginx_pkg_deb10
    volumes:
      - /var/tmp/weewx_html/html_pkg_deb10:/var/www/html/weewx
      - /var/tmp/weewx_archive/archive_pkg_deb10:/var/lib/weewx

  weewx_nginx_pkg_deb10:
    image: nginx
    container_name: weewx_nginx_pkg_deb10
    ports:
      - "8888:80"
    volumes:
      - /var/tmp/weewx_html/html_pkg_deb10:/usr/share/nginx/html

  #-----------------------------------------------------------------------
  #--- debian 10 installed via setup (python2) ---
  #-----------------------------------------------------------------------
  #
  #    webserver listens on 8887
  #
  # to build+run this pair:
  #    docker-compose up tar_deb10_py2
  #
  # to destroy and remove it:
  #    docker-compose down tar_deb10_py2

  weewx_setup_deb10_py2:
    tty: true
    build: build/setup_deb10_py2
    container_name: weewx_setup_deb10_py2
    image: weewx_setup_deb10_py2:latest
    depends_on:
      - weewx_nginx_setup_deb10_py2
    volumes:
      - /var/tmp/weewx_html/html_setup_deb10_py2:/home/weewx/public_html
      - /var/tmp/weewx_archive/archive_setup_deb10_py2:/home/weewx/archive

  weewx_nginx_setup_deb10_py2:
    image: nginx
    container_name: weewx_nginx_setup_deb10_py2
    ports:
      - "8887:80"
    volumes:
      - /var/tmp/weewx_html/html_setup_deb10_py2:/usr/share/nginx/html

#-- #---- uubuntu nginx listens on localhost:8081 ---
#-- 
#--   weenginx_uubuntu:
#--     image: nginx
#--     container_name: weenginx_uubuntu
#--     ports:
#--       - "8081:80"
#--     volumes:
#--       - ./public_html_uubuntu:/usr/share/nginx/html
#-- 
#--   weeubuntu:
#--     build: weeubuntu
#--     container_name: weeubuntu
#--     image: weeubuntu:3.9.1
#--     depends_on:
#--       - weenginx_uubuntu
#--     volumes:
#--       - ./public_html_uubuntu:/home/weewx/public_html
#--       - ./archive_uubuntu:/home/weewx/archive
#-- 
#-- #---- centos7 nginx listens on localhost:8082 ---
#-- 
#--   weenginx_centos7:
#--     image: nginx
#--     container_name: weenginx_centos7
#--     ports:
#--       - "8082:80"
#--     volumes:
#--       - ./public_html_centos7:/usr/share/nginx/html
#-- 
#--   weentos7:
#--     build: centos7
#--     container_name: weentos7
#--     image: weentos7:3.9.1
#--     depends_on:
#--       - weenginx_centos7
#--     volumes:
#--       - ./public_html_centos7:/home/weewx/public_html
#--       - ./archive_centos7:/home/weewx/archive
#-- 
#-- #---- centos6 nginx listens on localhost:8083 ---
#-- 
#--   weenginx_centos6:
#--     image: nginx
#--     container_name: weentos6
#--     container_name: weenginx_centos6
#--     ports:
#--       - "8083:80"
#--     volumes:
#--       - ./public_html_centos6:/usr/share/nginx/html
#-- 
#--   weentos6:
#--     build: centos6
#--     image: weentos6:3.9.1
#--     depends_on:
#--       - weenginx_centos6
#--     volumes:
#--       - ./public_html_centos6:/home/weewx/public_html
#--       - ./archive_centos6:/home/weewx/archive
#-- 
#----- that's all folks ----
